apiVersion: apps/v1
kind: Deployment
metadata:
  name: farmtoyou
spec:
  replicas: 3
  selector:
    matchLabels:
      app: farmtoyou
  template:
    metadata:
      labels:
        app: farmtoyou
    spec:
      containers:
        - name: farmtoyou
          image: limgs/farmtoyou:latest
          ports:
            - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: farmtoyou-service
spec:
  type: NodePort
  selector:
    app: farmtoyou
  ports:
    - port: 80
      targetPort: 3000
      nodePort: 30000
